# Generated by Django 5.2.4 on 2025-07-26 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_auto_20250725_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='Who this roll was dispatched to (if action=DISPATCH).', null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.customer'),
        ),
    ]
