# Generated by Django 5.2.4 on 2025-07-25 06:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_auto_20250723_1708'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='colour',
        ),
        migrations.RemoveField(
            model_name='material',
            name='thickness_unit',
        ),
        migrations.RemoveField(
            model_name='material',
            name='thickness_value',
        ),
        migrations.AddField(
            model_name='material',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='material',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, help_text='Which user first created this material', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='material',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Which department first registered this material', null=True, on_delete=django.db.models.deletion.PROTECT, to='warehouse.department'),
        ),
    ]
