# Generated by Django 5.2.4 on 2025-07-28 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_transaction_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReconciliationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_at', models.DateTimeField(auto_now_add=True)),
                ('is_clean', models.BooleanField(default=True, help_text='True if dashboard/API counts matched')),
                ('mismatches', models.TextField(blank=True, help_text="One line per location: e.g. 'FMA01: dash=8 vs api=7'")),
            ],
        ),
    ]
