# Generated by Django 5.2.4 on 2025-07-29 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0005_reconciliationlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_at', models.DateTimeField(auto_now_add=True)),
                ('total_rows', models.IntegerField()),
                ('imported', models.IntegerField()),
                ('skipped', models.IntegerField()),
                ('details', models.TextField(blank=True, help_text='One line per skipped row: material|batch')),
            ],
        ),
    ]
